version: "3.9"
services:
  backend:
    build: ./backend
    container_name: travel-agent-api
    ports:
      - "8000:8000"
      - "11434:11434"

  ui:
    build: ./frontend
    container_name: travel-agent-ui 
    ports:
      - "8501:8501"
    depends_on:
      - backend